### ISSUE TITLE
Unable to run REAVER

### ISSUE THREAD

**Issue by Pathancock** [uva-peirce-cottler-lab/public_REAVER#1]
Hello,

While following the instructions for running REAVER I get to step 6 'segment image' then the program freezes. 

The following error code shows up in MATLAB:
'segmentImage' is not found in the current folder or on the MATLAB path, but exists in:
    C:\Users\phancock\Documents\MATLAB\Examples\R2020a\deeplearning_shared\SemanticSegOfMultispectralImagesUsingDeepLearningExample

Change the MATLAB current folder or add its folder to the MATLAB path.

Error in REAVER_GUI>segmentationButton_Callback (line 1691)
	newHandles = segmentImage( handles ) ;
 
Error while evaluating UIControl Callback.

**Comment by bacorliss** [comment]
Hi,
    I am sorry for the delayed response and your troubles running REAVER. This appears to be a path management issue, did you run USER_INITIALIZE before running REAVER? All of the subfolders in the repository need to be added to the path for REAVER to function. The other possibility is that the working directory is required to point to the repository path for REAVER to run, which would not be an intended behavior. I will test this and get back to you.

**Comment by bacorliss** [comment]
It looks like REAVER is functioning fine with the working directory set elsewhere (at least with the limited tests I did). So my best guess is that the missing file is not included in MATLAB's path. Let me know if this helps. I would be happy to work with you if it does not until the problem gets resolved.
