### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by fangraymond** [uva-peirce-cottler-lab/public_REAVER#4]
This looks like a fascinating and useful program. However, when I try to download it via the link: "Download the latest version of REAVER from https://github.com/bacorliss/public_REAVER." I get a 404 not found error. Is this program still available for the public? Nice work!

**Comment by bac7wj** [comment]
I am sorry I did not see this sooner. On all github project pages there is a link with the latest release on the right side of the repository. The link I listed in the help section are indeed broken for the help file, the actual link is:

https://github.com/uva-peirce-cottler-lab/public_REAVER/releases/tag/v1.0.0
